name = "Ambercraft"
author = "Amber"
version = "0.4.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d726823cff640c2ff37db1c1bbb1981e8da679dc6c1bb7bef71de1e085a3441b"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
