name = "Ambercraft"
author = "Amber"
version = "0.2.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "92d225bbed9f8249520ad05131325c3328fd6f38488258875a8eafbaf6d641f0"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
