name = "Ambercraft"
author = "Amber"
version = "0.4.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8a18fc61cc4be4b04d3ee270a31b9e7969a6142f1b4917f41a9d3950244231ed"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
