StartupEvents.registry('item', event => {
  event.create('expedition_ledger')
  .displayName('Expedition Ledger')
  .rarity('uncommon')
  .maxStackSize(1)
  .glow(true)
  .texture('minecraft:item/knowledge_book')
  .tooltip(Text.gray('A heavy journal tracking the group\'s search for ancient eyes.'))
  .tooltip(Text.darkGreen('Right-click to inspect current clues.'))

  event.create('weathered_eye_chart')
  .displayName('Weathered Eye Chart')
  .rarity('uncommon')
  .glow(true)
  .texture('minecraft:item/map')

  event.create('rimebound_eye_shard')
  .displayName('Rimebound Eye Shard')
  .rarity('rare')
  .glow(true)
  .texture('minecraft:item/echo_shard')

  event.create('resonant_experience_rotor')
  .displayName('Resonant Experience Rotor')
  .rarity('epic')
  .maxStackSize(1)
  .glow(true)
  .texture('create_enchantment_industry:item/experience_rotor')
  .tooltip(Text.gray('A reusable heart for producing liquid hyper experience.'))
  .tooltip(Text.darkPurple('The mixer returns it after every batch.'))
})
